CREATE TABLE IF NOT EXISTS author (
	id BIGSERIAL PRIMARY KEY,
	name TEXT NOT NULL,
	surname TEXT NOT NULL,
	patronymic TEXT,
	birthday DATE NOT NULL,
	books BIGINT[]
);

CREATE TABLE IF NOT EXISTS genre (
	id BIGSERIAL PRIMARY KEY,
	name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS book (
	id BIGSERIAL PRIMARY KEY,
	ISBN CHAR(17) NOT NULL,
	genre BIGINT REFERENCES genre(id) NOT NULL
);
